## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [2]:
# 1) Seu código aqui
pc_mat = df_mat / 24
pc_por = df_por / 18
pc_geo = df_geo /  8
pc_ing = df_ing /  8
pc_his = df_his /  8
pc_fis = df_fis /  12
pc_qui = df_qui /  12

In [3]:
# 2) Seu código aqui
total_acertos = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui
total_acertos

    Qt_acertos
0           35
1           48
2           50
3           32
4           30
..         ...
95          34
96          27
97          40
98          40
99          42

[100 rows x 1 columns]

In [4]:
# 3) Seu código aqui
percentual_geral = total_acertos / 90
percentual_geral

    Qt_acertos
0     0.388889
1     0.533333
2     0.555556
3     0.355556
4     0.333333
..         ...
95    0.377778
96    0.300000
97    0.444444
98    0.444444
99    0.466667

[100 rows x 1 columns]

In [5]:
# 4) Seu código aqui
alunos_aprovados = (total_acertos > 45).sum()
alunos_aprovados

Qt_acertos    31
dtype: int64

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [6]:
# seu código aqui
eliminados = total_acertos[(df_mat['Qt_acertos'] == 0) |
                      (df_fis['Qt_acertos'] == 0) |
                      (df_qui['Qt_acertos'] == 0)]

eliminados

    Qt_acertos
3           32
6           29
10          31
12          42
14          31
20          53
25          27
26          40
27          50
33          39
35          48
49          19
56          39
65          24
66          31
72          50
73          37
74          39
84          26
89          63
92          40
94          25
98          40

In [7]:
eliminados = total_acertos[(df_mat['Qt_acertos'] == 0) |
                      (df_fis['Qt_acertos'] == 0) |
                      (df_qui['Qt_acertos'] == 0) |
                      (df_his['Qt_acertos'] == 8) |
                      (df_geo['Qt_acertos'] == 8)  ]
eliminados

    Qt_acertos
3           32
6           29
10          31
12          42
14          31
20          53
25          27
26          40
27          50
33          39
35          48
49          19
56          39
65          24
66          31
72          50
73          37
74          39
84          26
89          63
92          40
94          25
98          40

In [8]:
eliminados = total_acertos[(df_mat['Qt_acertos'] == 0) |
                      (df_fis['Qt_acertos'] == 0) |
                      (df_qui['Qt_acertos'] == 0) |
                      (df_his['Qt_acertos'] == 7) |
                      (df_geo['Qt_acertos'] == 7)  ]
eliminados.count()

Qt_acertos    47
dtype: int64

In [9]:
eliminados3 = total_acertos[(df_mat['Qt_acertos'] == 0) |
                       (df_por['Qt_acertos'] == 0) |
                       (df_geo['Qt_acertos'] == 0) |
                       (df_ing['Qt_acertos'] == 0) |
                       (df_his['Qt_acertos'] == 0) |
                       (df_fis['Qt_acertos'] == 0) |
                       (df_qui['Qt_acertos'] == 0) ]
eliminados3

    Qt_acertos
1           48
2           50
3           32
4           30
6           29
10          31
11          43
12          42
13          21
14          31
15          40
16          30
20          53
21          36
22          26
23          26
25          27
26          40
27          50
29          44
32          32
33          39
34          45
35          48
38          36
43          26
45          48
47          36
48          55
49          19
50          43
52          41
56          39
57          40
58          27
59          40
60          48
61          31
63          29
65          24
66          31
67          46
69          39
70          62
72          50
73          37
74          39
76          35
81          55
84          26
86          33
87          36
89          63
92          40
94          25
97          40
98          40
99          42

In [10]:
eliminados3 = total_acertos[(df_mat['Qt_acertos'] == 14) |
                       (df_por['Qt_acertos'] == 10) |
                       (df_geo['Qt_acertos'] == 5) |
                       (df_ing['Qt_acertos'] == 5) |
                       (df_his['Qt_acertos'] == 5) |
                       (df_fis['Qt_acertos'] == 7) |
                       (df_qui['Qt_acertos'] == 7) ]
eliminados3.count()

Qt_acertos    50
dtype: int64

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [11]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-e3ea46c5-877e-4acb-9d50-485897a9e115.c000.csv'

In [12]:
# 1) Sua solução aqui
df = pd.read_csv(arquivo, sep=';')

In [13]:
df.head()

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,b5775dbd-edb6-4c83-9bf6-6c48e2695dc0-i0b0,430bbbc3e8d76fe9532c6ddf2753015a4752b80932ef95...,17,2003-11-24,F,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,114.0,Outros,FD7210,PFIZER,Organization/00394544000851,2021-08-25,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
1,b28d339c-1843-4e4b-9816-e5148640e04f-i0b0,fe5f04b9378c8c48bca6420e125f1af12142d8001cbf13...,18,2003-07-03,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,219VCD267Z,ASTRAZENECA/FIOCRUZ,Organization/149,2022-02-11,Reforço,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
2,bd6fa4ea-1e32-4c8c-82c9-63dde9c011a4-i0b0,32970b5ac0b14940fb36421e34a9c150a5478c65a84d4b...,2,2021-02-15,F,5,INDIGENA,120032.0,10.0,JORDAO,...,7.0,Povos Indígenas,GX6964,PFIZER - PEDIÁTRICA MENOR DE 5 ANOS,28290,2023-08-08,1ª Dose,102,COVID-19 PFIZER - COMIRNATY PEDIÁTRICA MENOR D...,Novo PNI
3,b2913bb3-a0f4-4eef-adef-4e01aa9fd118-i0b0,50e84f32e07bf11d7edb825ee8e220a82d2e7746923416...,23,1999-01-16,F,1,BRANCA,120017.0,10.0,CAPIXABA,...,2.0,Faixa Etária,FJ4187,PFIZER,Organization/28290,2022-01-31,Reforço,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
4,f33e843e-9a89-4063-8eba-563d7911adf5-i0b0,ca560063af89d30785818b01295560dda15464afce4cc6...,20,2001-03-01,M,3,PARDA,120020.0,10.0,CRUZEIRO DO SUL,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-09,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [14]:
df.shape[0]

388670

In [15]:
# 2)
df['paciente_id'].nunique()

317501

In [16]:
# 3)
primeira_dose = df['vacina_descricao_dose'].unique()[0]
df['paciente_id'].loc[df['vacina_descricao_dose'] == primeira_dose].nunique()

120420

In [17]:
# 3) solução alternativa
primeira_dose = df['vacina_descricao_dose'].unique()[0]
df_primeira_dose = df[df['vacina_descricao_dose'] == primeira_dose]
df_primeira_dose['paciente_id'].nunique()

120420

In [18]:
# 4)
df_menor = df[df["paciente_idade"]<18]
df_menor['paciente_id'].nunique()

68925

In [19]:
# 5)
df['estabelecimento_razaoSocial'].nunique()

63

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [20]:
# 1)
df_menor = df[df["paciente_idade"]<18].copy()

In [21]:
# 2)
df_menor.columns.tolist()

['document_id',
 'paciente_id',
 'paciente_idade',
 'paciente_dataNascimento',
 'paciente_enumSexoBiologico',
 'paciente_racaCor_codigo',
 'paciente_racaCor_valor',
 'paciente_endereco_coIbgeMunicipio',
 'paciente_endereco_coPais',
 'paciente_endereco_nmMunicipio',
 'paciente_endereco_nmPais',
 'paciente_endereco_uf',
 'paciente_endereco_cep',
 'paciente_nacionalidade_enumNacionalidade',
 'estabelecimento_valor',
 'estabelecimento_razaoSocial',
 'estalecimento_noFantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf',
 'vacina_grupoAtendimento_codigo',
 'vacina_grupoAtendimento_nome',
 'vacina_categoria_codigo',
 'vacina_categoria_nome',
 'vacina_lote',
 'vacina_fabricante_nome',
 'vacina_fabricante_referencia',
 'vacina_dataAplicacao',
 'vacina_descricao_dose',
 'vacina_codigo',
 'vacina_nome',
 'sistema_origem']

In [22]:
# 3)
df_menor['vacina_categoria_nome'].value_counts()

vacina_categoria_nome
Faixa Etária                                      48134
Povos Indígenas                                    4760
Outros                                             3755
Povos e Comunidades Tradicionais                    874
Trabalhadores de Saúde                              264
Comorbidades                                         57
População Privada de Liberdade                       53
Gestantes                                            45
Trabalhadores da Educação                            14
Trabalhadores de Transporte                          13
Pessoas com Deficiência                              11
Pessoas Institucionalizadas                           3
Pessoas de 60 anos ou mais institucionalizadas        1
Puérperas                                             1
Name: count, dtype: int64

In [23]:
# 4)
lista_variaveis = ['estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf']
lista_variaveis

['estabelecimento_valor',
 'estabelecimento_razaoSocial',
 'estalecimento_noFantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']

In [24]:
# 5)
df_menor_lista = df_menor.loc[:,lista_variaveis]
df_menor_lista

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
0,2000555,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE BASICA DE SAUDE PENTECOSTES,120020,CRUZEIRO DO SUL,AC
2,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
5,7139454,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE DA FAMILIA FLUVIAL MARIETA CA...,120020,CRUZEIRO DO SUL,AC
7,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
8,924490,PREFEITURA MUNICIPAL DE FEIJO,UNIDADE MOVEL DE SAUDE FLUVIAL PEDRO RODRIGUES...,120030,FEIJO,AC
...,...,...,...,...,...,...
388630,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
388639,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
388657,2002566,PREFEITURA MUNICIPAL DE SENA MADUREIRA,UNIDADE BASICA DE SAUDE LAURO FONTES DA SILVA,120050,SENA MADUREIRA,AC
388668,2002876,SECRETARIA MUNCIPAL DE SAUDE,CENTRO DE SAUDE RAIMUNDA PORFIRIO DE BRITO RAMOS,120013,BUJARI,AC
388669,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC

In [25]:
# 6)
df_menor_lista = df_menor_lista.drop_duplicates()
df_menor_lista

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
0,2000555,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE BASICA DE SAUDE PENTECOSTES,120020,CRUZEIRO DO SUL,AC
2,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
5,7139454,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE DA FAMILIA FLUVIAL MARIETA CA...,120020,CRUZEIRO DO SUL,AC
7,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
8,924490,PREFEITURA MUNICIPAL DE FEIJO,UNIDADE MOVEL DE SAUDE FLUVIAL PEDRO RODRIGUES...,120030,FEIJO,AC
...,...,...,...,...,...,...
313347,755605,USF BARRO VERMELHO,USF BARRO VERMELHO,120040,RIO BRANCO,AC
336157,6411312,PREFEITURA MUNICIPAL DE PLACIDO DE CASTRO,U S F LUCIO ALVES DA SILVA,120038,PLACIDO DE CASTRO,AC
353199,2000814,SECRETARIA DE ESTADO DE SAUDE DO ACRE,USF FRANCISCO EDUARDO DE PAIVA,120040,RIO BRANCO,AC
364764,2832798,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,UNIDADE DE SAUDE ALBERTO FLORENCIO DA SILVA,120025,EPITACIOLANDIA,AC
388619,7565089,PREFEITURA MUNICIPAL DE RIO BRANCO,USF MARIA DE JESUS III,120040,RIO BRANCO,AC

In [26]:
df_menor_lista.shape

(211, 6)